dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: rom-import-8
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom61
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom62
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom63
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
